FROM node:16

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# Instale o nodemon globalmente
RUN npm install -g nodemon

COPY . .

EXPOSE 3000

# Use nodemon para iniciar o aplicativo
CMD ["sh", "-c", "npm run test && nodemon src/index.js"]
